name: tazkiyah_os
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tazkiyah_core:
    path: packages/core
  tazkiyah_identity:
    path: packages/identity
  tazkiyah_journey:
    path: packages/journey
  tazkiyah_knowledge:
    path: packages/knowledge
  tazkiyah_practice:
    path: packages/practice
  tazkiyah_reflection:
    path: packages/reflection

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.8
